apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-emll
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0034-tenant/ci10t-786-0034-app/devfile-sample-emll@sha256:eb5f8c7d4a97ee421b376e4a7452eea46dfa59b8b1684e5ccf112a5ace350b90
        name: my-nodejs
        resources: {}
status: {}
